### PR TITLE
Match autosync payee

### PR DESCRIPTION
**Pull request by 501st-alpha1**
This is my attempt at implementing payee matching for #25.  I've implemented it for the plain Ledger interface, and haven't (yet) done so for the Python interface or HLedger.  (I've been having some trouble getting the Python interface to work with ledger-autosync, and I haven't gotten around to installing HLedger yet.)  I added non-fatal stub functions for those two so that it's backwards-compatible at least.

If you're okay with the stubs and want to merge this as is, feel free, otherwise I can try to implement those too.

### CODE REVIEW

**Comment by egh** [comment]
Closing & re-opening to trigger travis build.

**Comment by kotp** [comment]
Closing and re-opening to trigger is not necessary, as you have write access to this repository.  From the travis page targetted by "Details" for the job, there is a "Restart Job" button.

**Comment by egh** [comment]
@kotp Good to know, thanks!

**Comment by 501st-alpha1** [comment]
@egh I've rebased this onto `master`, fixed an issue causing tests to fail, and have also added a test for my new matching functionality.

**Comment by egh** [comment]
@501st-alpha1 Thank you!

**Pull request merged**
